program Soft;

{$I DEFINE.INC}

uses
  Windows,
  SysUtils,
  Forms,
  Registry,
  OnGuard,
  OgUtil,
  MAIN in 'EnvSet\MAIN.PAS' {MainForm},
  WSCustomRpt in '..\..\Public\Template\WSCustomRpt.pas' {WSCustomReport: TQuickRep},
  WSBrowse in '..\..\Public\Template\WSBrowse.pas' {WSBrowseForm},
  WSEdit in '..\..\Public\Template\WSEdit.pas' {WSEditForm},
  WSVoucherRpt in '..\..\Public\Template\WSVoucherRpt.pas' {VoucherReport: TQuickRep},
  WSStandardEdit in '..\..\Public\Template\WSStandardEdit.pas' {WSStandardEditForm},
  WSVoucherBrowse in '..\..\Public\Template\WSVoucherBrowse.pas' {WSVoucherBrowseForm},
  WSVoucherEdit in '..\..\Public\Template\WSVoucherEdit.pas' {WSVoucherEditForm},
  WSStandardBrowse in '..\..\Public\Template\WSStandardBrowse.pas' {WSStandardBrowseForm},
  WSUtils in '..\..\Public\PubFunc\WSUtils.pas',
  WSConsts in '..\..\Public\PubFunc\WSConsts.pas',
  CommonDM in 'CommonDM.pas' {CommonData: TDataModule},
  WSCstFrm in '..\..\Public\Template\WSCstFrm.pas' {WSCustomForm},
  MSOption in 'Ms\MSOption.pas' {MSOptionForm},
  WSTreeView in '..\..\Public\Template\WSTreeView.pas' {WSTreeViewForm},
  MSPermissions in 'Ms\MSPermissions.pas' {MSPermissionsForm},
  MSEdCurrency in 'Ms\MSEdCurrency.pas' {MSEdCurrencyForm},
  MSBrCurrency in 'Ms\MSBrCurrency.pas' {MSBrCurrencyForm},
  WSLogin in '..\..\Public\CustomVcl\WSLogin.pas' {WSLoginForm},
  WSSecurity in '..\..\Public\CustomVcl\WSSecurity.PAS',
  DABrAreas in 'Da\DABrAreas.pas' {DAAreasBrowseForm},
  DAEdAreas in 'Da\DAEdAreas.pas' {DAAreasEditForm},
  MSEdDepartment in 'Ms\MSEdDepartment.pas' {MSDepartmentEditForm},
  MSBrDepartment in 'Ms\MSBrDepartment.pas' {MSDepartmentBrowseForm},
  MSEdEmployee in 'Ms\MSEdEmployee.pas' {MSEdEmployeeForm: WSEdSales},
  MSBrRoles in 'Ms\MSBrRoles.pas' {MSBrRolesForm},
  MSEdUser in 'Ms\MSEdUser.pas' {MSEdUserForm},
  MSEdUserTerm in 'Ms\MSEdUserTerm.pas' {MSEdUserTermForm},
  MSEdUserAddTerm in 'Ms\MSEdUserAddTerm.pas' {MSEdUserAddTermForm},
  DABrmanufacturer in 'Da\DABrmanufacturer.pas' {DABrmanufacturerForm},
  DAEdmanufacturer in 'Da\DAEdmanufacturer.pas' {DAEdmanufacturerForm},
  DABrGoodsClasses in 'Da\DABrGoodsClasses.pas' {DAGoodsClassesBrowseForm},
  DAEdGoodsClass in 'Da\DAEdGoodsClass.pas' {DAGoodsClassEditForm},
  DABrGoods in 'Da\DABrGoods.pas' {DAGoodsBrowseForm},
  DAEdGoods in 'Da\DAEdGoods.pas' {DAGoodsEditForm},
  MSEdTermAddUser in 'Ms\MSEdTermAddUser.pas' {MSEdTermAddUserForm},
  FNEdAccounts in 'Fn\FNEdAccounts.pas' {FNEditAccountsForm},
  FNBrAccounts in 'Fn\FNBrAccounts.pas' {FNBrAccountsForm},
  MSEdPostion in 'Ms\MSEdPostion.pas' {MSEdPostionForm},
  MSEdUserPermissions in 'Ms\MSEdUserPermissions.pas' {MSUserPermissionsEditForm},
  DAAttributeEdit in 'Da\DAAttributeEdit.pas' {DAAttributeEditForm},
  DABrAccountCode in 'Da\DABrAccountCode.pas' {DABrAccountCodeForm},
  DAEdSubject in 'Da\DAEdSubject.pas' {DAEdSubjectForm},
  DAAttributeBr in 'Da\DAAttributeBr.pas' {DAAttributeBrForm},
  MSBrLogin in 'Ms\MSBrLogin.pas' {MSBrLoginForm},
  Navigator in 'Navigator.pas' {NavigatorForm},
  MSBrPostionClass in 'Ms\MSBrPostionClass.pas' {MSPostionClassBrowseForm},
  MSEdPostionClass in 'Ms\MSEdPostionClass.pas' {MSPostionClassEditForm},
  MSBrPostion in 'Ms\MSBrPostion.pas' {MSPostionBrowseForm},
  MSBrUnits in 'Ms\MSBrUnits.pas' {MSBrUnitForm},
  MSEdUnit in 'Ms\MSEdUnit.pas' {MSEdUnitForm},
  DABillType in 'Da\DABillType.pas' {DABillTypeForm},
  MSPeriod in 'Ms\MSPeriod.pas' {MSPeriodForm},
  DABrExpenseClass in 'Da\DABrExpenseClass.pas' {DABrExpenseClassForm},
  DAEdExpenseClass in 'Da\DAEdExpenseClass.pas' {DAEdExpenseClassForm},
  DABrPOClear in 'Da\DABrPOClear.pas' {DABrPOClearForm},
  DAEdPOClear in 'Da\DAEdPOClear.pas' {DAEdPOClearForm},
  SLBrSalePrice in 'Sl\SLBrSalePrice.pas' {SLBrSalePriceForm},
  SLEdSalePrice in 'Sl\SLEdSalePrice.pas' {SLEdSalePriceForm},
  SLBrCredit in 'Sl\SLBrCredit.pas' {SLCreditBrowseForm},
  SLEdCredit in 'Sl\SLEdCredit.pas' {SLCreditEditForm},
  PCEdCredit in 'Pc\PCEdCredit.pas' {PCCreditEditForm},
  PCBrCredit in 'Pc\PCBrCredit.pas' {PCCreditBrowseForm},
  DABrLinkMenIDCard in 'Da\DABrLinkMenIDCard.pas' {DALinkMenIDCardBrowseForm},
  DAEdLinkMenIDCard in 'Da\DAEdLinkMenIDCard.pas' {DALinkMenIDCardEditForm},
  SLBrContract in 'Sl\SLBrContract.pas' {SLBrContractForm},
  SLEdContract in 'Sl\SLEdContract.pas' {SLEdContractForm},
  PCEdContract in 'Pc\PCEdContract.pas' {PCEdContractForm},
  PCBrContract in 'Pc\PCBrContract.pas' {PCBrContractForm},
  DABrLinkMen in 'Da\DABrLinkMen.pas' {DALinkMemBrowseForm},
  OABrJobRecords in 'Oa\OABrJobRecords.pas' {OABrJobRecordsForm},
  OAEdJobRecords in 'Oa\OAEdJobRecords.pas' {OAEdJobRecordsForm},
  OABrJobRecordsMng in 'Oa\OABrJobRecordsMng.pas' {OABrJobRecordsMngForm},
  SLBrSaleGift in 'Sl\SLBrSaleGift.pas' {SLBrSaleGiftForm},
  SLEdSaleGift in 'Sl\SLEdSaleGift.pas' {SLEdSaleGiftForm},
  OABrJobArrange in 'Oa\OABrJobArrange.pas' {OABrJobArrangeForm},
  OAEdJobArrange in 'Oa\OAEdJobArrange.pas' {OAEdJobArrangeForm},
  About in 'About.pas' {AboutForm},
  FNBrExpense in 'Fn\FNBrExpense.pas' {FNBrExpenseForm},
  FNEdExpense in 'Fn\FNEdExpense.pas' {FNEdExpenseForm},
  STEdCountOff in 'St\STEdCountOff.pas' {STEdCountOffForm},
  SLBrContractPrice in 'Sl\SLBrContractPrice.pas' {SLBrContractPriceForm},
  DAEdClient in 'Da\DAEdClient.pas' {DAClientEditForm},
  DABrClient in 'Da\DABrClient.pas' {DAClientBrowseForm},
  DABrClientkRelation in 'Da\DABrClientkRelation.pas' {DAClientkRelationBrowseForm},
  DABrClientK in 'Da\DABrClientK.pas' {DAClientkBrowseForm},
  OAEdCompanyNews in 'Oa\OAEdCompanyNews.pas' {OAEdCompanyNewsForm},
  OABrCompanyNews in 'Oa\OABrCompanyNews.pas' {OABrCompanyNewsForm},
  DABrClientc in 'Da\DABrClientc.pas' {DAClientcBrowseForm},
  DABrClientcRelation in 'Da\DABrClientcRelation.pas' {DAClientcRelationBrowseForm},
  YDBrPW in 'Yd\YDBrPW.pas' {YDBrPWForm},
  YDEdPW in 'Yd\YDEdPW.pas' {YDEdPWForm},
  YDBrProductPlan in 'Yd\YDBrProductPlan.pas' {YDBrProductPlanForm},
  YDEdProductPlan in 'Yd\YDEdProductPlan.pas' {YDEdProductPlanForm},
  YDBrBalanceOf in 'Yd\YDBrBalanceOf.pas' {YDBrBalanceForm},
  YDEdBalanceOf in 'Yd\YDEdBalanceOf.pas' {YDEdBalanceOfForm},
  YDBrExpressBalance in 'Yd\YDBrExpressBalance.pas' {YDBrExpressBalanceForm},
  SLDiscountMode in 'Sl\SLDiscountMode.pas' {SLDiscountModeForm},
  SLOrderTail in 'Sl\SLOrderTail.pas' {SLOrderTailForm},
  SLEdSaleS in 'Sl\SLEdSaleS.pas' {SLEdSaleSForm},
  SLBrSaleS in 'Sl\SLBrSaleS.pas' {SLBrSaleSForm},
  FNBrClearSL in 'Fn\FNBrClearSL.pas' {FNBrClearSLForm},
  FNEdClearSL in 'Fn\FNEdClearSL.pas' {FNEdClearSLForm},
  SLBrSaleB in 'Sl\SLBrSaleB.pas' {SLBrSaleBForm},
  SLEdSaleB in 'Sl\SLEdSaleB.pas' {SLEdSaleBForm},
  SLEdOrder in 'Sl\SLEdOrder.pas' {SLEdOrderForm},
  SLBrOrder in 'Sl\SLBrOrder.pas' {SLBrOrderForm},
  SLBrGoodsOut in 'Sl\SLBrGoodsOut.pas' {SLBrGoodsOutForm},
  SLEdGoodsOut in 'Sl\SLEdGoodsOut.pas' {SLEdGoodsOutForm},
  PCBrContractPrice in 'Pc\PCBrContractPrice.pas' {PCBrContractPriceForm},
  BaseVoucherEdit in 'BaseVoucherEdit.pas' {BaseVoucherEditForm},
  VoucherQuery in 'VoucherQuery.pas' {VoucherQueryForm},
  SLBrDiscount in 'Sl\SLBrDiscount.pas' {SLBrDiscountForm},
  SLEdDiscount in 'Sl\SLEdDiscount.pas' {SLEdDiscountForm},
  RpCustomize in 'Rp\RpCustomize.pas' {RpCustomizeForm},
  SLEdGoodsOutB in 'Sl\SLEdGoodsOutB.pas' {SLEdGoodsOutBForm},
  SLBrGoodsOutB in 'Sl\SLBrGoodsOutB.pas' {SLBrGoodsOutBForm},
  PCBrOrder in 'Pc\PCBrOrder.pas' {PCBrOrderForm},
  PCEdOrder in 'Pc\PCEdOrder.pas' {PCEdOrderForm},
  PCEdPurchase in 'Pc\PCEdPurchase.pas' {PCEdPurchaseForm},
  PCBrPurchase in 'Pc\PCBrPurchase.pas' {PCBrPurchaseForm},
  PCEdPurchaseB in 'Pc\PCEdPurchaseB.pas' {PCEdPurchaseBForm},
  PCBrPurchaseB in 'Pc\PCBrPurchaseB.pas' {PCBrPurchaseBForm},
  PCEdGoodsIn in 'Pc\PCEdGoodsIn.pas' {PCEdGoodsInForm},
  PCBrGoodsIn in 'Pc\PCBrGoodsIn.pas' {PCBrGoodsInForm},
  FNEdClearPC in 'Fn\FNEdClearPC.pas' {FNEdClearPCForm},
  FNBrClearPC in 'Fn\FNBrClearPC.pas' {FNBrClearPCForm},
  PCEdGoodsInB in 'Pc\PCEdGoodsInB.pas' {PCEdGoodsInBForm},
  PCBrGoodsInB in 'Pc\PCBrGoodsInB.pas' {PCBrGoodsInBForm},
  PCEdContractPrice in 'Pc\PCEdContractPrice.pas' {PCEdContractPriceForm},
  SLEdContractPrice in 'Sl\SLEdContractPrice.pas' {SLEdContractPriceForm},
  FNBrCashIn in 'Fn\FNBrCashIn.pas' {FNBrCashInForm},
  FNBrCashOut in 'Fn\FNBrCashOut.pas' {FNBrCashOutForm},
  FNEdCashOut in 'Fn\FNEdCashOut.pas' {FNEdCashOutForm},
  FNEdCashIn in 'Fn\FNEdCashIn.pas' {FNEdCashInForm},
  YDEdGoodsIn in 'Yd\YDEdGoodsIn.pas' {YDEdGoodsInForm},
  YDBrGoodsIn in 'Yd\YDBrGoodsIn.pas' {YDBrGoodsInForm},
  YDEdGoodsOut in 'Yd\YDEdGoodsOut.pas' {YDEdGoodsOutForm},
  YDBrGoodsOut in 'Yd\YDBrGoodsOut.pas' {YDBrGoodsOutForm},
  FNEdCashOutIn in 'Fn\FNEdCashOutIn.pas' {FNEdCashOutInForm},
  FNBrCashOutIn in 'Fn\FNBrCashOutIn.pas' {FNBrCashOutInForm},
  STBrGoodsOutIn in 'St\STBrGoodsOutIn.pas' {STBrGoodsOutInForm},
  STEdGoodsOutIn in 'St\STEdGoodsOutIn.pas' {STEdGoodsOutInForm},
  STStockChange in 'St\STStockChange.pas' {STStockChangeFrom},
  FNActualCash in 'Fn\FNActualCash.pas' {FNActualCashFrom},
  FNCashFlow in 'Fn\FNCashFlow.pas' {FNCashFlowForm},
  FNCashLeger in 'Fn\FNCashLeger.pas' {FNCashLegerForm},
  FNExpenseRep in 'Fn\FNExpenseRep.pas' {FNExpenseRepForm},
  FNReceiptPayable in 'Fn\FNReceiptPayable.pas' {FNReceiptPayableFrom},
  FNReceiptPayLeger in 'Fn\FNReceiptPayLeger.pas' {FNReceiptPayLegerForm},
  FNReceiptPayLegerE in 'Fn\FNReceiptPayLegerE.pas' {FNReceiptPayLegerEForm},
  FNReceiptPayableE in 'Fn\FNReceiptPayableE.pas' {FNReceiptPayableEFrom},
  FNBalanceSheet in 'Fn\FNBalanceSheet.pas' {FNBalanceSheetForm},
  FNProfitLoss in 'Fn\FNProfitLoss.pas' {FNProfitLossForm},
  SLBrSale in 'Sl\SLBrSale.pas' {SLBrSaleForm},
  SLEdSale in 'Sl\SLEdSale.pas' {SLEdSaleForm},
  STEdGoodsCountOff in 'St\STEdGoodsCountOff.pas' {STEdGoodsCountOffForm},
  STBrGoodsCountOff in 'St\STBrGoodsCountOff.pas' {STBrGoodsCountOffForm},
  SREdJobs in 'SR\SREdJobs.pas' {SREdJobsForm},
  SREdJobPrice in 'SR\SREdJobPrice.pas' {SREdJobPriceForm},
  SRBrJobPrice in 'SR\SRBrJobPrice.pas' {SRBrJobPriceForm},
  BaseVoucherRpt in 'BaseVoucherRpt.pas' {BaseVoucherReport: TQuickRep},
  SREdWorkQuantity in 'SR\SREdWorkQuantity.pas' {SREdWorkQuantityForm},
  SRBrWorkQuantity in 'SR\SRBrWorkQuantity.pas' {SRBrWorkQuantityForm},
  SREdBaseSalary in 'SR\SREdBaseSalary.pas' {SREdBaseSalaryForm},
  SRBrBaseSalary in 'SR\SRBrBaseSalary.pas' {SRBrBaseSalaryForm},
  YDEdFormula in 'Yd\YDEdFormula.pas' {YDEdFormulaForm},
  YDBrFormula in 'Yd\YDBrFormula.pas' {YDBrFormulaForm},
  YDEdPurchasePlan in 'Yd\YDEdPurchasePlan.pas' {YDEdPurchasePlanForm},
  YDBrPurchasePlan in 'Yd\YDBrPurchasePlan.pas' {YDBrPurchasePlanForm},
  YDBOMBack in 'Yd\YDBOMBack.pas' {YDBOMBackFrom},
  YDStockInWork in 'Yd\YDStockInWork.pas' {YDStockInWorkFrom},
  SLSaleFruitList in 'Sl\SLSaleFruitList.pas' {SLSaleFruitListForm},
  PCPurchaseFruitList in 'Pc\PCPurchaseFruitList.pas' {PCPurchaseFruitListForm},
  SRBrWorkTime in 'SR\SRBrWorkTime.pas' {SRBrWorkTimeForm},
  SREdWorkTime in 'SR\SREdWorkTime.pas' {SREdWorkTimeForm},
  SRBrWorkSchedule in 'SR\SRBrWorkSchedule.pas' {SRBrWorkScheduleForm},
  SREdWorkSchedule in 'SR\SREdWorkSchedule.pas' {SREdWorkScheduleForm},
  SREdWorkRest in 'SR\SREdWorkRest.pas' {SREdWorkRestForm},
  SRBrWorkRest in 'SR\SRBrWorkRest.pas' {SRBrWorkRestForm},
  SLEdSaleClient in 'Sl\SLEdSaleClient.pas' {SLEdSaleClientForm},
  SLBrSaleClient in 'Sl\SLBrSaleClient.pas' {SLBrSaleClientForm},
  WSVoucherImport in 'WSVoucherImport.pas' {WSVoucherImportForm},
  SREdWorkTimeCnt in 'SR\SREdWorkTimeCnt.pas' {SREdWorkTimeCntForm},
  SRBrWorkTimeCnt in 'SR\SRBrWorkTimeCnt.pas' {SRBrWorkTimeCntForm},
  SLSaleChainList in 'Sl\SLSaleChainList.pas' {SLSaleChainListForm},
  SRSalaryAnalyze in 'SR\SRSalaryAnalyze.pas' {SRSalaryAnalyzeForm},
  FAEdAssetAdd in 'Fa\FAEdAssetAdd.pas' {FAEdAssetAddForm},
  FABrAssetAdd in 'Fa\FABrAssetAdd.pas' {FABrAssetAddForm},
  FABrDepreciation in 'Fa\FABrDepreciation.pas' {FABrDepreciationForm},
  FAEdDepreciation in 'Fa\FAEdDepreciation.pas' {FAEdDepreciationForm},
  FNAssetRept in 'Fa\FNAssetRept.pas' {FNAssetReptFrom},
  MSBrEmployee in 'Ms\MSBrEmployee.pas' {MSBrEmployeeForm},
  FAEdAssetReduce in 'Fa\FAEdAssetReduce.pas' {FAEdAssetReduceForm},
  FABrAssetReduce in 'Fa\FABrAssetReduce.pas' {FABrAssetReduceForm},
  BaseVoucherEditA in 'BaseVoucherEditA.pas' {BaseVoucherEditAForm},
  FAEdAssetRepair in 'Fa\FAEdAssetRepair.pas' {FAEdAssetRepairForm},
  FABrAssetRepair in 'Fa\FABrAssetRepair.pas' {FABrAssetRepairForm},
  FABrAssetRePlan in 'Fa\FABrAssetRePlan.pas' {FABrAssetRePlanForm},
  FAEdAssetRePlan in 'Fa\FAEdAssetRePlan.pas' {FAEdAssetRePlanForm},
  FAAssetChange in 'Fa\FAAssetChange.pas' {FAAssetChangeFrom},
  FAAssetPlanRept in 'Fa\FAAssetPlanRept.pas' {FAAssetPlanReptFrom},
  YDDailyReport in 'Yd\YDDailyReport.pas' {YDDailyReportForm},
  YDStatisticReport in 'Yd\YDStatisticReport.pas' {YDStatisticReportForm},
  MSEdUserNew in 'Ms\MSEdUserNew.pas' {MSEdUserNewForm},
  MSBrUserNew in 'Ms\MSBrUserNew.pas' {MSBrUserNewForm},
  SRBrJobs in 'SR\SRBrJobs.pas' {SRBrJobsForm},
  FNAccountAgeSL in 'Fn\FNAccountAgeSL.pas' {FNAccountAgeSLForm},
  SLSaleForeCast in 'Sl\SLSaleForeCast.pas' {SLSaleForeCastForm},
  WSVoucherEditSY in '..\..\Public\Template\WSVoucherEditSY.pas' {WSVoucherEditSYForm},
  PCPurchaseStatistic in 'Pc\PCPurchaseStatistic.pas' {PCPurchaseStatisticForm},
  SLSaleStatistic in 'Sl\SLSaleStatistic.pas' {SLSaleStatisticForm},
  PCPurchaseForeCast in 'Pc\PCPurchaseForeCast.pas' {PCPurchaseForeCastForm},
  SLRpSale in 'Sl\SLRpSale.pas' {SLSaleVoucherReport: TQuickRep},
  PCEdPurchasePrice in 'Pc\PCEdPurchasePrice.pas' {PCedPurchasePriceForm},
  PCBrPurchasePrice in 'Pc\PCBrPurchasePrice.pas' {PCBrPurchasePriceForm},
  SLEdSaleGTP in 'Sl\SLEdSaleGTP.pas' {SLEdSaleGTPForm},
  SLEdOrderGTP in 'Sl\SLEdOrderGTP.pas' {SLEdOrderGTPForm},
  SLEdSaleBGTP in 'Sl\SLEdSaleBGTP.pas' {SLEdSaleBGTPForm},
  SLEdGoodsOutGTP in 'Sl\SLEdGoodsOutGTP.pas' {SLEdGoodsOutGTPForm},
  SLEdGoodsOutBGTP in 'Sl\SLEdGoodsOutBGTP.pas' {SLEdGoodsOutBGTPForm},
  SLEdSaleClientGTP in 'Sl\SLEdSaleClientGTP.pas' {SLEdSaleClientGTPForm},
  PCEdGoodsInGTP in 'Pc\PCEdGoodsInGTP.pas' {PCEdGoodsInGTPForm},
  PCEdGoodsInBGTP in 'Pc\PCEdGoodsInBGTP.pas' {PCEdGoodsInBGTPForm},
  PCEdOrderGTP in 'Pc\PCEdOrderGTP.pas' {PCEdOrderGTPForm},
  PCEdPurchaseGTP in 'Pc\PCEdPurchaseGTP.pas' {PCEdPurchaseGTPForm},
  PCEdPurchaseBGTP in 'Pc\PCEdPurchaseBGTP.pas' {PCEdPurchaseBGTPForm},
  YDEdGoodsInGTP in 'Yd\YDEdGoodsInGTP.pas' {YDEdGoodsInGTPForm},
  YDEdGoodsOutGTP in 'Yd\YDEdGoodsOutGTP.pas' {YDEdGoodsOutGTPForm},
  STEdGoodsCountOffGTP in 'St\STEdGoodsCountOffGTP.pas' {STEdGoodsCountOffGTPForm},
  STEdGoodsOutInGTP in 'St\STEdGoodsOutInGTP.pas' {STEdGoodsOutInGTPForm},
  MSDataRestore in 'Ms\MSDataRestore.pas' {MSDataRestoreForm},
  VoucherImport in 'VoucherImport.pas' {VoucherImportForm},
  MSEdUserPassWord in 'Ms\MSEdUserPassWord.pas' {MSEdUserPassWordForm},
  DAProjectBrowse in 'EG\DAProjectBrowse.pas' {DAProjectBrowseForm},
  DAProjectEdit in 'EG\DAProjectEdit.pas' {DAProjectEditForm},
  EGExpenseStatistic in 'EG\EGExpenseStatistic.pas' {EGExpenseStatisticForm},
  DAEdWarehouse in 'Da\DAEdWarehouse.pas' {DAEdWarehouseForm},
  DABrWarehouse in 'Da\DABrWarehouse.pas' {DABrWarehouseForm},
  DABrProjectClass in 'Da\DABrProjectClass.pas' {DAProjectClassBrowseForm},
  DAEdProjectClass in 'Da\DAEdProjectClass.pas' {DAProjectClassEditForm},
  DABrProject in 'Da\DABrProject.pas' {DABrProjectForm},
  DAEdProject in 'Da\DAEdProject.pas' {DAEdProjectForm},
  DASubject in 'Da\DASubject.pas' {DASubjectForm},
  DAEdAccountCode in 'Da\DAEdAccountCode.pas' {DAEdAccountCodeForm},
  AboutZW in 'AboutZW.pas' {AboutZWForm},
  FNBrCredence in 'Fn\FNBrCredence.pas' {FNCredenceBrowseForm},
  FNEdCredence in 'Fn\FNEdCredence.pas' {FNCredenceEditForm},
  FNExpenseSttc in 'Fn\FNExpenseSttc.pas' {FNExpenseSttcForm},
  FNAccountAgePC in 'Fn\FNAccountAgePC.pas' {FNAccountAgePCForm},
  WSDateRangeFm in '..\..\Public\Template\WSDateRangeFm.pas' {WSDateRangeFrame: TFrame},
  FNRptCustomize in 'Fn\FNRptCustomize.pas' {FNCustomizeReportForm},
  FNRptSubjectCollect in 'Fn\FNRptSubjectCollect.pas' {FNSubjectCollectReportForm},
  FNRptSubjectDetailCollect in 'Fn\FNRptSubjectDetailCollect.pas' {FNSubjectDetailsCollectReportForm},
  WSRptFrm in '..\..\Public\Template\WSRptFrm.pas' {WSReportForm},
  FNRptSubjectDetails in 'Fn\FNRptSubjectDetails.pas' {FNSubjectDetailsReportForm},
  STBrPCGoodsInCost in 'St\STBrPCGoodsInCost.pas' {STBrPCGoodsInCostForm},
  STEdPCGoodsInCost in 'St\STEdPCGoodsInCost.pas' {STEdPCGoodsInCostForm},
  FNBrVouchTran in 'Fn\FNBrVouchTran.pas' {FNBrVouchTranForm},
  FNEdVouchTran in 'Fn\FNEdVouchTran.pas' {FNEdVouchTranForm},
  FNVouchTranIni in 'Fn\FNVouchTranIni.pas' {FNVouchTranIniForm},
  STActualStock in 'St\STActualStock.pas' {STActualStockForm},
  STNewStockRep in 'St\STNewStockRep.pas' {STNewStockRepForm},
  SLRpCheckReckoning in 'Sl\SLRpCheckReckoning.pas' {SLCheckReckoningReport: TQuickRep},
  PCRpCheckReckoning in 'Pc\PCRpCheckReckoning.pas' {PCCheckReckoningReport: TQuickRep},
  STEdSLGoodsOutCost in 'St\STEdSLGoodsOutCost.pas' {STEdSLGoodsOutCostForm},
  STBrSLGoodsOutCost in 'St\STBrSLGoodsOutCost.pas' {STBrSLGoodsOutCostForm},
  STBrYDGoodsInCost in 'St\STBrYDGoodsInCost.pas' {STBrYDGoodsInCostForm},
  STEdYDGoodsInCost in 'St\STEdYDGoodsInCost.pas' {STEdYDGoodsInCostForm},
  EGEdGoodsOutGTP in 'EG\EGEdGoodsOutGTP.pas' {EGEdGoodsOutGTPForm},
  EGEdGoodsOut in 'EG\EGEdGoodsOut.pas' {EGEdGoodsOutForm},
  EGBrGoodsOut in 'EG\EGBrGoodsOut.pas' {EGBrGoodsOutForm},
  FNEdClearEG in 'Fn\FNEdClearEG.pas' {FNEdClearEGForm},
  FNBrClearEG in 'Fn\FNBrClearEG.pas' {FNBrClearEGForm},
  EGProjectStatistic in 'EG\EGProjectStatistic.pas' {EGProjectStatisticForm},
  SLEdSaleCloth in 'SL\SLEdSaleCloth.pas' {SLEdSaleClothForm},
  SLBrSaleCloth in 'SL\SLBrSaleCloth.pas' {SLBrSaleClothForm},
  PCBrPurchaseCloth in 'Pc\PCBrPurchaseCloth.pas' {PCBrPurchaseClothForm},
  PCEDPurchaseCloth in 'Pc\PCEDPurchaseCloth.pas' {PCEDPurchaseClothForm},
  STBrClothOutIn in 'St\STBrClothOutIn.pas' {STBrClothOutInForm},
  STEdClothOutIn in 'St\STEdClothOutIn.pas' {STEdClothOutInForm},
  STEdClothCountOff in 'St\STEdClothCountOff.pas' {STEdClothCountOffForm},
  STBRClothCountOff in 'St\STBRClothCountOff.pas' {STBRClothCountOffForm},
  SLSaleClothStatistic in 'SL\SLSaleClothStatistic.pas' {SLSaleClothStatisticForm},
  PCPurchaseClothStatistic in 'Pc\PCPurchaseClothStatistic.pas' {PCPurchaseClothStatisticForm},
  STClothStockRep in 'St\STClothStockRep.pas' {STClothStockRepForm},
  STBrYDGoodsOutCost in 'St\STBrYDGoodsOutCost.pas' {STBrYDGoodsOutCostForm},
  STEdYDGoodsOutCost in 'St\STEdYDGoodsOutCost.pas' {STEdYDGoodsOutCostForm},
  SLBrSaleDsct in 'SL\SLBrSaleDsct.pas' {SLBrSaleDsctForm},
  SLEdSaleDsct in 'SL\SLEdSaleDsct.pas' {SLEdSaleDsctForm},
  SLEdSaleDsctGTP in 'SL\SLEdSaleDsctGTP.pas' {SLEdSaleDsctGTPForm},
  FNBrCashExchange in 'Fn\FNBrCashExchange.pas' {FNBrCashExchangeForm},
  FNEdCashExchange in 'Fn\FNEdCashExchange.pas' {FNEdCashExchangeForm},
  FNCashExchStatistic in 'Fn\FNCashExchStatistic.pas' {FNCashExchStatisticForm},
  FNEdCashInFRG in 'Fn\FNEdCashInFRG.pas' {FNEdCashInFRGForm},
  FNEdCashOutFRG in 'Fn\FNEdCashOutFRG.pas' {FNEdCashOutFRGForm},
  FNEdExpenseFRG in 'Fn\FNEdExpenseFRG.pas' {FNEdExpenseFRGForm},
  FNEdClearEGFRG in 'Fn\FNEdClearEGFRG.pas' {FNEdClearEGFRGForm},
  FNEdClearPCFRG in 'Fn\FNEdClearPCFRG.pas' {FNEdClearPCFRGForm},
  FNEdClearSLFRG in 'Fn\FNEdClearSLFRG.pas' {FNEdClearSLFRGForm};

{$R *.RES}

{$IFDEF TRIAL}
var
  CKey: TKey = ($214);
  Code: TCode; S: string;
{$ENDIF}
begin
{$IFDEF TRIAL}
  S := 'NoCode';
  with TRegistry.Create do
  try
    RootKey := HKEY_CLASSES_ROOT;
    if OpenKey('CLSID\' + GUIDToString(TGUID(CKey)) + '\Codes', True) then
      if ValueExists('DaysCode') then S := ReadString('DaysCode');
    if S = 'NoCode' then
    begin
      InitDaysCode(CKey, 30, EncodeDate(2003, 12, 31), Code);
      S := BufferToHex(Code, SizeOf(Code));
    end
    else HexToBuffer(S, Code, SizeOf(Code));
    if not IsDaysCodeValid(CKey, Code) then
      raise Exception.Create('×¢²áÂë´íÎó');
    DecDaysCode(CKey, Code);
    if IsDaysCodeExpired(CKey, Code) then
    begin
      Application.MessageBox('±¾²úÆ·ÉÐÎ´ÊÚÈ¨!', '',
        MB_ICONINFORMATION or MB_OK);
      Exit;
    end;
    S := BufferToHex(Code, SizeOf(Code));
    WriteString('DaysCode', S);
  finally
    Free;
  end;
{$ENDIF}

  Application.Initialize;
  Application.Title := 'ERP';
  Application.CreateForm(TCommonData, CommonData);
  Application.CreateForm(TMainForm, MainForm);
  Guarder.Close;
  Guarder.Open;
  MainForm.DisableMenuItems(MainForm.MainMenu.Items);
  Application.Run;
end.
